const keywords = [
  "vente en ligne",
  "Tunisie",
  "offres exclusives",
  "promotions",
  "achat en ligne",
  "produits Tunisie",
  "Ita-Luxury",
  "nouveaux produits",
  "produits en promotion",
  "achat sécurisé",
  "livraison rapide",
  "meilleures offres",
  "produits électroniques",
  "mode et accessoires",
  "équipements maison",
  "meilleures marques",
  "produits de qualité",
  "shopping en ligne",
  "e-commerce Tunisie",
  "boutique en ligne",
  "cadeaux",
  "vente flash",
  "meilleur prix",
  "offre spéciale",
  "dernière chance",
  "satisfaction garantie",
  "service clientèle",
  "commande facile",
  "paiement sécurisé",
  "articles populaires",
  "beauté et bien-être",
  "jouets pour enfants",
  "décoration intérieure",
  "accessoires informatiques",
  "produits de jardinage",
  "vêtements pour hommes",
  "vêtements pour femmes",
  "chaussures de qualité",
  "accessoires de mode",
  "idées de cadeaux",
  "articles de cuisine",
  "outils de bricolage",
  "meubles modernes",
  "produits de santé",
  "accessoires pour animaux",
  "montres de luxe",
  "bijoux élégants",
  "sacs à main tendance",
  "panier d'achat",
  "finaliser commande",
  "récapitulatif commande",
  "frais de livraison",
  "options de paiement",
  "code promo",
  "réduction panier",
  "continuer vos achats",
  "total commande",
  "taxes incluses",
  "confirmation commande",
  "suivi de commande",
  "politique de retour",
  "garantie satisfaction",
  "assistance panier",
  "paiement sécurisé",
  "options de paiement",
  "finaliser la commande",
  "récapitulatif de commande",
  "confirmation de paiement",
  "processus de commande",
  "checkout en ligne",
  "achat sécurisé",
  "paiement en ligne Tunisie",
  "commande facile",
];

export default keywords;
